global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ace'
    static_configs:
      - targets: ['ace:3000']
    metrics_path: '/sas-cag/v1/metrics'
    scrape_interval: 10s
